In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# carregando dataset
df = pd.read_csv('Data/Retail_Transactions_Dataset.csv')

# visualizando as primeiras 5 linhas 
df.head()

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
0,1000000000,2022-01-21 06:27:29,Stacey Price,"['Ketchup', 'Shaving Cream', 'Light Bulbs']",3,71.65,Mobile Payment,Los Angeles,Warehouse Club,True,Homemaker,Winter,NaN
1,1000000001,2023-03-01 13:01:21,Michelle Carlson,"['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'P...",2,25.93,Cash,San Francisco,Specialty Store,True,Professional,Fall,BOGO (Buy One Get One)
2,1000000002,2024-03-21 15:37:04,Lisa Graves,['Spinach'],6,41.49,Credit Card,Houston,Department Store,True,Professional,Winter,NaN
3,1000000003,2020-10-31 09:59:47,Mrs. Patricia May,"['Tissues', 'Mustard']",1,39.34,Mobile Payment,Chicago,Pharmacy,True,Homemaker,Spring,NaN
4,1000000004,2020-12-10 00:59:59,Susan Mitchell,['Dish Soap'],10,16.42,Debit Card,Houston,Specialty Store,False,Young Adult,Winter,Discount on Selected Items

In [9]:
total_itens = df['Total_Items'].sum()
faturamento_total = df['Total_Cost'].sum()

print(f"Total de itens vendidos: {total_itens}")
print(f"Faturamento Total: R$ {faturamento_total:.2f}")

Total de itens vendidos: 5495941
Faturamento Total: R$ 52455220.40

In [11]:
vendas_por_loja = df.groupby('Store_Type')['Total_Items'].sum().reset_index()
vendas_por_loja['Percentual'] = (vendas_por_loja['Total_Items'] / total_itens) * 100

print(vendas_por_loja)

          Store_Type  Total_Items  Percentual
0  Convenience Store       918049   16.704128
1   Department Store       915635   16.660204
2           Pharmacy       917729   16.698305
3    Specialty Store       914950   16.647741
4        Supermarket       915772   16.662697
5     Warehouse Club       913806   16.626925

In [12]:
custo_por_loja = df.groupby('Store_Type')['Total_Cost'].sum().reset_index()
faturamento_global = df['Total_Cost'].sum()
custo_por_loja['% do Custo Total'] = (custo_por_loja['Total_Cost'] / faturamento_global) * 100

print("--- Custos por Tipo de Loja ---")
print(custo_por_loja)

--- Custos por Tipo de Loja ---
          Store_Type  Total_Cost  % do Custo Total
0  Convenience Store  8731901.36         16.646392
1   Department Store  8731555.57         16.645732
2           Pharmacy  8766679.01         16.712691
3    Specialty Store  8701600.22         16.588626
4        Supermarket  8763455.21         16.706545
5     Warehouse Club  8760029.03         16.700014

In [13]:
pagamentos = df['Payment_Method'].value_counts()

print("\n--- Uso dos Métodos de Pagamento ---")
print(pagamentos)

print(f"\nO método MAIS usado é: {pagamentos.idxmax()}")
print(f"O método MENOS usado é: {pagamentos.idxmin()}")

--- Uso dos Métodos de Pagamento ---
Payment_Method
Cash              250230
Debit Card        250074
Credit Card       249985
Mobile Payment    249711
Name: count, dtype: int64

O método MAIS usado é: Cash
O método MENOS usado é: Mobile Payment

In [15]:
media_custo = df['Total_Cost'].mean()
# filtrando somente as compras acima da média e vendo os métodos
compras_caras = df[df['Total_Cost'] > media_custo]['Payment_Method'].value_counts()

print(f"Média de custo: R$ {media_custo:.2f}")
print("\nMétodos usados em compras acima da média:")
print(compras_caras)

Média de custo: R$ 52.46

Métodos usados em compras acima da média:
Payment_Method
Cash              125048
Credit Card       125013
Mobile Payment    124949
Debit Card        124622
Name: count, dtype: int64

In [20]:
df['Date'] = pd.to_datetime(df['Date'])

df['Hora'] = df['Date'].dt.hour
df['Dia_Semana'] = df['Date'].dt.day_name()

# Vendas por hora (quais horários o pessoal mais compra?)
vendas_hora = df['Hora'].value_counts().sort_index()

# Vendas por dia da semana
vendas_dia = df['Dia_Semana'].value_counts()

print("--- Vendas por Hora ---")
print(vendas_hora)

print("\n--- Vendas por Dia da Semana ---")
print(vendas_dia)

--- Vendas por Hora ---
Hora
0     41416
1     41224
2     41617
3     41917
4     41768
5     41574
6     41508
7     41521
8     41926
9     41841
10    42021
11    41154
12    41790
13    41817
14    41739
15    41819
16    41505
17    41655
18    41843
19    41646
20    41674
21    41894
22    41433
23    41698
Name: count, dtype: int64

--- Vendas por Dia da Semana ---
Dia_Semana
Thursday     143375
Friday       143367
Saturday     143310
Wednesday    143104
Monday       142435
Tuesday      142317
Sunday       142092
Name: count, dtype: int64

In [21]:
# Criando uma tabela dinâmica para ver o volume de vendas
# Linhas: Cidade | Colunas: Hora | Valores: Contagem de transações
vendas_cidade_hora = df.pivot_table(index='City', columns='Hora', values='Transaction_ID', aggfunc='count')

# Mostrando as primeiras cidades para conferir
vendas_cidade_hora.head()

Hora,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
City,,,,,,,,,,,,,,,,,,,,,
Atlanta,4098,4139,4209,4200,4198,4105,4018,4053,4197,4168,...,4132,4104,4114,4110,4123,4000,4147,4189,4101,4111
Boston,4171,4205,4042,4255,4266,4172,4196,4049,4211,4204,...,4214,4208,4258,4200,4199,4103,4102,4314,4161,4260
Chicago,4219,4164,4247,4132,4210,4131,4108,4168,4212,4183,...,4258,4084,4114,4238,4244,4183,4095,4186,4083,4308
Dallas,4164,4087,4147,4160,4057,4245,4227,4241,4210,4189,...,4230,4209,4179,4176,4230,4174,4184,4239,4187,4232
Houston,4156,4198,4258,4231,4077,4198,4114,4162,4142,4175,...,4091,4165,4168,4112,4210,4164,4242,4229,4230,4163

In [23]:
# Criando um novo DataFrame apenas com Convenience Store
df_conv = df[df['Store_Type'] == 'Convenience Store'].copy()

# Verificando o tamanho da nossa amostra
print(f"Total de vendas no setor de Conveniência: {len(df_conv)}")

Total de vendas no setor de Conveniência: 166749